name: trackify
description: "Trackify - Personal Finance & Expense Tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  firebase_auth: ^6.2.0
  firebase_core: ^4.5.0
  cloud_firestore: ^6.1.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  image_path: assets/logo.png
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#0A2342"
    theme_color: "#0A2342"

flutter:
  uses-material-design: true

  assets:
   - assets/
